name: CI

on: push

jobs:
  maven-project:
    name: Build and test the Java project 
    runs-on: ubuntu-latest
    steps:
    - name: Checkout files in the repository
      uses: actions/checkout@v3

    - name: Setup Java 
      uses: actions/setup-java@v3
      with:
        distribution: 'zulu'
        java-version: '17'

    - name: Build and Test 
      run: mvn -U clean verify
